apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: battleforcastile-gateway
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - auth.battleforcastile.com
        - match-recorder.battleforcastile.com
      secretName: letsencrypt-prod
  rules:
  - host: auth.battleforcastile.com
    http:
      paths:
      - backend:
          serviceName: battleforcastile-auth-service
          servicePort: {{ .Values.service.port }}
  - host: match-recorder.battleforcastile.com
    http:
      paths:
      - backend:
          serviceName: battleforcastile-match-recorder-service
          servicePort: {{ .Values.service.port }}